"""
Trains the two small random-forest regressors behind Ripple's adaptive
difficulty engine, then transpiles them to plain JS via m2cgen so they run
directly inside a Vercel serverless function / the client — no separate
inference server. (Originally scoped as gradient-boosted trees; switched to
RandomForestRegressor because m2cgen doesn't support sklearn's
GradientBoostingRegressor — random forest stays within pure scikit-learn
with no new dependency, and performs comparably at this feature-set size.)

Model A (focus score): learns to approximate the interpretable honest-
scoring formula from session features. Starts as a learned copy of that
formula; once real telemetry accumulates in S3, retraining on it lets the
model diverge from the formula and better reflect actual player behavior.

Model B (next difficulty): predicts where next round's difficulty ramp
should start (0..1) from this round's performance — the actual adaptive
piece, replacing a fixed one-size-fits-all curve.
"""

import json

import m2cgen as m2c
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

df = pd.read_csv("data/synthetic_sessions.csv")

FOCUS_FEATURES = [
    "reactionTimeMeanMs",
    "reactionTimeStdMs",
    "falseTapRate",
    "missRate",
    "targetSwitchAccuracy",
]
DIFFICULTY_FEATURES = FOCUS_FEATURES + ["startProgress", "focusScore"]


def train_and_report(features, target, name):
    X = df[features]
    y = df[target]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Kept small on purpose: m2cgen transpiles every tree into nested
    # if/else JS, so tree count x depth directly bloats the shipped bundle.
    model = RandomForestRegressor(n_estimators=20, max_depth=5, random_state=42)
    model.fit(X_train, y_train)

    preds = model.predict(X_test)
    print(f"[{name}] R^2 = {r2_score(y_test, preds):.3f}, MAE = {mean_absolute_error(y_test, preds):.3f}")

    model.fit(X, y)  # refit on all data for the exported model
    return model


focus_model = train_and_report(FOCUS_FEATURES, "focusScore", "focusScore")
difficulty_model = train_and_report(DIFFICULTY_FEATURES, "nextStartProgress", "nextStartProgress")

for model, features, out_name in [
    (focus_model, FOCUS_FEATURES, "focusScoreModel"),
    (difficulty_model, DIFFICULTY_FEATURES, "difficultyModel"),
]:
    js_code = m2c.export_to_javascript(model, function_name="predict")
    wrapped = f"""// Auto-generated by ml/train.py via m2cgen — do not edit by hand.
// Feature order: {json.dumps(features)}
{js_code}
module.exports = {{ predict, featureOrder: {json.dumps(features)} }};
"""
    out_path = f"../src/lib/ml/{out_name}.js"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(wrapped)
    print(f"Wrote {out_path}")
