import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by next-pwa at build time — not source.
    "public/sw.js",
    "public/workbox-*.js",
    "public/fallback-*.js",
    // Auto-generated by ml/train.py via m2cgen — not hand-written source.
    "src/lib/ml/focusScoreModel.js",
    "src/lib/ml/difficultyModel.js",
    // Separate Python project (training scripts + its own venv), not app source.
    "ml/**",
  ]),
]);

export default eslintConfig;
